version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb2
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobsportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haris123
    ports:
      - "5432:5432"
    networks:
      - backend

  microservice2:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: microservice2
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/jobsportal
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=haris123
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
    command: ./gradlew quarkusDev -Dquarkus.http.host=0.0.0.0

networks:
  backend:
    driver: bridge
